/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "assets/compiled/telegram.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(TelegramMain, TelegramMain, AUTO)


PB_BIND(DialogRequest, DialogRequest, AUTO)


PB_BIND(DialogResponse, DialogResponse, AUTO)


PB_BIND(MessagesRequest, MessagesRequest, AUTO)


PB_BIND(MessagesResponse, MessagesResponse, AUTO)


PB_BIND(SendMessageRequest, SendMessageRequest, AUTO)


PB_BIND(Dialog, Dialog, AUTO)


PB_BIND(Message, Message, AUTO)


PB_BIND(Update, Update, AUTO)



