/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_ASSETS_COMPILED_TELEGRAM_PB_H_INCLUDED
#define PB_ASSETS_COMPILED_TELEGRAM_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _DialogResponse { 
    pb_callback_t dialogs; 
} DialogResponse;

typedef struct _MessagesResponse { 
    pb_callback_t msgs; 
} MessagesResponse;

typedef struct _Dialog { 
    int64_t id; 
    pb_callback_t name; 
} Dialog;

typedef struct _DialogRequest { 
    int32_t count; 
} DialogRequest;

typedef struct _Message { 
    pb_callback_t text; 
    bool is_our; 
} Message;

typedef struct _MessagesRequest { 
    int64_t id; 
    int32_t count; 
} MessagesRequest;

typedef struct _SendMessageRequest { 
    int64_t id; 
    pb_callback_t msg; 
} SendMessageRequest;

typedef struct _Update { 
    int64_t id; 
    bool has_msg;
    Message msg; 
} Update;

typedef struct _TelegramMain { 
    uint32_t message_type; 
    pb_size_t which_content;
    union {
        DialogRequest dialog_request;
        DialogResponse dialog_response;
        MessagesRequest messages_request;
        MessagesResponse messages_response;
        SendMessageRequest send_message_request;
        Update update;
    } content; 
} TelegramMain;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define TelegramMain_init_default                {0, 0, {DialogRequest_init_default}}
#define DialogRequest_init_default               {0}
#define DialogResponse_init_default              {{{NULL}, NULL}}
#define MessagesRequest_init_default             {0, 0}
#define MessagesResponse_init_default            {{{NULL}, NULL}}
#define SendMessageRequest_init_default          {0, {{NULL}, NULL}}
#define Dialog_init_default                      {0, {{NULL}, NULL}}
#define Message_init_default                     {{{NULL}, NULL}, 0}
#define Update_init_default                      {0, false, Message_init_default}
#define TelegramMain_init_zero                   {0, 0, {DialogRequest_init_zero}}
#define DialogRequest_init_zero                  {0}
#define DialogResponse_init_zero                 {{{NULL}, NULL}}
#define MessagesRequest_init_zero                {0, 0}
#define MessagesResponse_init_zero               {{{NULL}, NULL}}
#define SendMessageRequest_init_zero             {0, {{NULL}, NULL}}
#define Dialog_init_zero                         {0, {{NULL}, NULL}}
#define Message_init_zero                        {{{NULL}, NULL}, 0}
#define Update_init_zero                         {0, false, Message_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define DialogResponse_dialogs_tag               1
#define MessagesResponse_msgs_tag                1
#define Dialog_id_tag                            1
#define Dialog_name_tag                          2
#define DialogRequest_count_tag                  1
#define Message_text_tag                         1
#define Message_is_our_tag                       2
#define MessagesRequest_id_tag                   1
#define MessagesRequest_count_tag                2
#define SendMessageRequest_id_tag                1
#define SendMessageRequest_msg_tag               2
#define Update_id_tag                            1
#define Update_msg_tag                           2
#define TelegramMain_message_type_tag            1
#define TelegramMain_dialog_request_tag          2
#define TelegramMain_dialog_response_tag         3
#define TelegramMain_messages_request_tag        4
#define TelegramMain_messages_response_tag       5
#define TelegramMain_send_message_request_tag    6
#define TelegramMain_update_tag                  7

/* Struct field encoding specification for nanopb */
#define TelegramMain_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   message_type,      1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (content,dialog_request,content.dialog_request),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (content,dialog_response,content.dialog_response),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (content,messages_request,content.messages_request),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (content,messages_response,content.messages_response),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (content,send_message_request,content.send_message_request),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (content,update,content.update),   7)
#define TelegramMain_CALLBACK NULL
#define TelegramMain_DEFAULT NULL
#define TelegramMain_content_dialog_request_MSGTYPE DialogRequest
#define TelegramMain_content_dialog_response_MSGTYPE DialogResponse
#define TelegramMain_content_messages_request_MSGTYPE MessagesRequest
#define TelegramMain_content_messages_response_MSGTYPE MessagesResponse
#define TelegramMain_content_send_message_request_MSGTYPE SendMessageRequest
#define TelegramMain_content_update_MSGTYPE Update

#define DialogRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    count,             1)
#define DialogRequest_CALLBACK NULL
#define DialogRequest_DEFAULT NULL

#define DialogResponse_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  dialogs,           1)
#define DialogResponse_CALLBACK pb_default_field_callback
#define DialogResponse_DEFAULT NULL
#define DialogResponse_dialogs_MSGTYPE Dialog

#define MessagesRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT64,    id,                1) \
X(a, STATIC,   SINGULAR, INT32,    count,             2)
#define MessagesRequest_CALLBACK NULL
#define MessagesRequest_DEFAULT NULL

#define MessagesResponse_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  msgs,              1)
#define MessagesResponse_CALLBACK pb_default_field_callback
#define MessagesResponse_DEFAULT NULL
#define MessagesResponse_msgs_MSGTYPE Message

#define SendMessageRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT64,    id,                1) \
X(a, CALLBACK, SINGULAR, STRING,   msg,               2)
#define SendMessageRequest_CALLBACK pb_default_field_callback
#define SendMessageRequest_DEFAULT NULL

#define Dialog_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT64,    id,                1) \
X(a, CALLBACK, SINGULAR, STRING,   name,              2)
#define Dialog_CALLBACK pb_default_field_callback
#define Dialog_DEFAULT NULL

#define Message_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   text,              1) \
X(a, STATIC,   SINGULAR, BOOL,     is_our,            2)
#define Message_CALLBACK pb_default_field_callback
#define Message_DEFAULT NULL

#define Update_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT64,    id,                1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  msg,               2)
#define Update_CALLBACK NULL
#define Update_DEFAULT NULL
#define Update_msg_MSGTYPE Message

extern const pb_msgdesc_t TelegramMain_msg;
extern const pb_msgdesc_t DialogRequest_msg;
extern const pb_msgdesc_t DialogResponse_msg;
extern const pb_msgdesc_t MessagesRequest_msg;
extern const pb_msgdesc_t MessagesResponse_msg;
extern const pb_msgdesc_t SendMessageRequest_msg;
extern const pb_msgdesc_t Dialog_msg;
extern const pb_msgdesc_t Message_msg;
extern const pb_msgdesc_t Update_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define TelegramMain_fields &TelegramMain_msg
#define DialogRequest_fields &DialogRequest_msg
#define DialogResponse_fields &DialogResponse_msg
#define MessagesRequest_fields &MessagesRequest_msg
#define MessagesResponse_fields &MessagesResponse_msg
#define SendMessageRequest_fields &SendMessageRequest_msg
#define Dialog_fields &Dialog_msg
#define Message_fields &Message_msg
#define Update_fields &Update_msg

/* Maximum encoded size of messages (where known) */
/* TelegramMain_size depends on runtime parameters */
/* DialogResponse_size depends on runtime parameters */
/* MessagesResponse_size depends on runtime parameters */
/* SendMessageRequest_size depends on runtime parameters */
/* Dialog_size depends on runtime parameters */
/* Message_size depends on runtime parameters */
/* Update_size depends on runtime parameters */
#define DialogRequest_size                       11
#define MessagesRequest_size                     22

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
